# Generated by Django 4.1.4 on 2022-12-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(default='Addis Ababa', max_length=80)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
