# Generated by Django 4.1.4 on 2022-12-19 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_perso_delete_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Perso',
            new_name='Person',
        ),
    ]
