# Generated by Django 4.1.4 on 2022-12-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_perso_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='Addis Ababa', max_length=254),
            preserve_default=False,
        ),
    ]
