# Generated by Django 4.1.4 on 2022-12-19 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_person_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
    ]
