# Generated by Django 4.1.4 on 2022-12-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_person_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='address',
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='email', max_length=254),
            preserve_default=False,
        ),
    ]
