# Generated by Django 4.1.4 on 2022-12-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_person_address_person_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
    ]
