# Generated by Django 4.1.4 on 2022-12-16 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_name_menuitems_itemname'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='menuitems',
            old_name='year',
            new_name='price',
        ),
        migrations.AddField(
            model_name='menuitems',
            name='category_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='myapp.menucategory'),
        ),
    ]
