# Generated by Django 4.1.4 on 2022-12-16 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_menucategory_rename_year_menuitems_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='category_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='category_name', to='myapp.menucategory'),
        ),
    ]
